version: '3.7'

services:
  nginx:
    build:
      context: ./.docker/nginx/
    container_name: nginx
    ports:
    - 81:80
    restart: always
    volumes:
    - ./.docker/nginx/logs:/var/log/nginx/
    - .:/var/www/html
    depends_on:
    - php
    networks:
    - app-network

  php:
    build:
      context: ./.docker/php/
    container_name: php
    restart: always
    env_file:
    - ./.env
    volumes:
    - ./.docker/php/app/cache:/var/www/dev/app/cache/:rw
    - ./.docker/php/app/logs:/var/www/dev/app/logs/:rw
    - ./.docker/.composer:/var/www/.composer
    - .:/var/www/html
    networks:
    - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
